# <font color='CC3D3D'> 0.6_6 OverSamplinig SMOTE
    
- train 데이터에서 0과 1 비율을 5:5로 맞춰줌 (0 : 1 = 1,631,225 : 1,631,225)
- SMOTE 알고리즘을 사용해 희소 label의 양을 늘려 label 균형을 맞춰주는 데이터를 생성하는 코드
- 불균형 해소 데이터 <span style="color:blue"> **master_train_oversample.csv** </span> 생성

# Import

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.datasets import make_classification
from sklearn.model_selection import cross_validate
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.ensemble import RandomForestClassifier

from imblearn.pipeline import Pipeline
from imblearn.combine import SMOTETomek
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import TomekLinks

from sklearn.metrics import classification_report, confusion_matrix

import scipy
from sklearn.svm import SVC

# Data Load

In [2]:
train_undersample = pd.read_csv('../Data/master_train_undersample.csv')
test_undersample = pd.read_csv('../Data/master_test_undersample.csv')

In [3]:
X_train = train_undersample.drop('is_applied', axis=1)
y_train = train_undersample['is_applied']

In [4]:
# SMOTE 객체 생성
smote = SMOTE(random_state=42)

# 샘플링
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

In [6]:
X_train_resampled

,loan_limit,loan_rate,credit_score,yearly_income,income_type,employment_type,houseown_type,desired_amount,purpose,personal_rehabilitation_yn,...,loan_limit_max_x,loan_rate_max_x,bank_label,loan_limit_min_y,loan_rate_min_y,loan_limit_max_y,loan_rate_max_y,loan_limit_mean_y,loan_rate_mean_y,product_label
0,2.300000e+07,12.900000,960.000000,2.300000e+07,0,1,3,2.400000e+07,1,0.0,...,7.000000e+07,19.400000,2,3.000000e+06,5.900000,7.000000e+07,19.400000,2.805744e+07,13.546706,0
1,2.000000e+07,12.900000,590.000000,2.500000e+07,0,3,3,2.000000e+07,6,0.0,...,1.500000e+08,15.000000,1,1.000000e+06,6.700000,1.500000e+08,15.000000,2.898214e+07,12.349341,0
2,1.100000e+07,17.900000,750.000000,2.000000e+07,0,2,0,3.000000e+06,7,0.0,...,1.000000e+08,19.900000,0,5.000000e+06,11.900000,5.000000e+07,19.900000,2.322836e+07,14.940214,0
3,6.000000e+06,7.800000,720.000000,4.300000e+07,0,0,3,5.000000e+07,7,0.0,...,8.000000e+07,19.100000,2,2.000000e+06,5.200000,2.000000e+07,9.200000,1.211133e+07,7.844548,1
4,3.900000e+07,13.300000,800.000000,5.000000e+07,0,3,2,5.000000e+07,7,0.0,...,1.000000e+08,19.900000,2,3.000000e+06,6.800000,1.000000e+08,19.700000,3.614451e+07,13.070143,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3262445,3.806033e+06,6.034339,730.999298,3.100754e+07,0,3,1,1.526114e+07,7,0.0,...,1.000000e+10,19.500000,2,1.000000e+06,4.900000,1.000000e+10,19.500000,1.926253e+07,8.716201,0
3262446,1.608961e+07,14.261300,575.376669,3.164156e+07,0,3,2,2.268833e+06,2,0.0,...,1.000000e+08,18.261300,2,2.089611e+06,8.267011,1.000000e+08,17.715067,2.846996e+07,11.928606,0
3262447,4.769242e+07,9.276869,867.438052,4.974360e+07,3,1,2,2.743603e+07,7,0.0,...,1.000000e+08,14.651229,1,2.487205e+06,5.820471,1.000000e+08,14.651229,2.641281e+07,9.336623,0
3262448,8.000000e+06,8.500000,600.000000,3.500000e+07,0,3,0,5.000000e+06,5,0.0,...,1.000000e+08,19.500000,2,2.000000e+06,5.700000,2.000000e+07,9.000000,1.145343e+07,7.499008,1
3262449,1.249282e+07,7.881327,742.629948,2.502873e+07,0,3,3,2.246409e+07,7,0.0,...,1.000000e+08,18.074145,2,2.000000e+06,7.781327,2.000000e+07,9.753591,1.218597e+07,7.975459,1

In [8]:
y_train_resampled.value_counts()

0.0    1631225
1.0    1631225
Name: is_applied, dtype: int64

In [10]:
master_train_oversample = pd.concat([X_train_resampled, y_train_resampled], axis=1)

## Deployment

In [11]:
master_train_oversample.to_csv('../Data/master_train_oversample.csv', index=False)

In [12]:
pd.read_csv('../Data/master_train_oversample.csv')

,loan_limit,loan_rate,credit_score,yearly_income,income_type,employment_type,houseown_type,desired_amount,purpose,personal_rehabilitation_yn,...,loan_rate_max_x,bank_label,loan_limit_min_y,loan_rate_min_y,loan_limit_max_y,loan_rate_max_y,loan_limit_mean_y,loan_rate_mean_y,product_label,is_applied
0,2.300000e+07,12.900000,960.000000,2.300000e+07,0,1,3,2.400000e+07,1,0.0,...,19.400000,2,3.000000e+06,5.900000,7.000000e+07,19.400000,2.805744e+07,13.546706,0,0.0
1,2.000000e+07,12.900000,590.000000,2.500000e+07,0,3,3,2.000000e+07,6,0.0,...,15.000000,1,1.000000e+06,6.700000,1.500000e+08,15.000000,2.898214e+07,12.349341,0,1.0
2,1.100000e+07,17.900000,750.000000,2.000000e+07,0,2,0,3.000000e+06,7,0.0,...,19.900000,0,5.000000e+06,11.900000,5.000000e+07,19.900000,2.322836e+07,14.940214,0,0.0
3,6.000000e+06,7.800000,720.000000,4.300000e+07,0,0,3,5.000000e+07,7,0.0,...,19.100000,2,2.000000e+06,5.200000,2.000000e+07,9.200000,1.211133e+07,7.844548,1,0.0
4,3.900000e+07,13.300000,800.000000,5.000000e+07,0,3,2,5.000000e+07,7,0.0,...,19.900000,2,3.000000e+06,6.800000,1.000000e+08,19.700000,3.614451e+07,13.070143,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3262445,3.806033e+06,6.034339,730.999298,3.100754e+07,0,3,1,1.526114e+07,7,0.0,...,19.500000,2,1.000000e+06,4.900000,1.000000e+10,19.500000,1.926253e+07,8.716201,0,1.0
3262446,1.608961e+07,14.261300,575.376669,3.164156e+07,0,3,2,2.268833e+06,2,0.0,...,18.261300,2,2.089611e+06,8.267011,1.000000e+08,17.715067,2.846996e+07,11.928606,0,1.0
3262447,4.769242e+07,9.276869,867.438052,4.974360e+07,3,1,2,2.743603e+07,7,0.0,...,14.651229,1,2.487205e+06,5.820471,1.000000e+08,14.651229,2.641281e+07,9.336623,0,1.0
3262448,8.000000e+06,8.500000,600.000000,3.500000e+07,0,3,0,5.000000e+06,5,0.0,...,19.500000,2,2.000000e+06,5.700000,2.000000e+07,9.000000,1.145343e+07,7.499008,1,1.0
3262449,1.249282e+07,7.881327,742.629948,2.502873e+07,0,3,3,2.246409e+07,7,0.0,...,18.074145,2,2.000000e+06,7.781327,2.000000e+07,9.753591,1.218597e+07,7.975459,1,1.0